###############################################################################
#                                                    #
# microuser 20170130    Manaully edit for conversion to version 2 from phpdocker.io
#   -   Remove Ports on webserver, replace with link nginx-proxy
#   -   Add depends_on nginx-proxy
#   -   Move domain-php-fpm dockerfile into build: dockerfile:
###############################################################################
version: '2'

services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
         - 80:80
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
         - ./docker/nginx-proxy/conf.d/xdebug.conf:/etc/nginx/conf.d/xdebug.conf

    regexpatterns-webserver:
      image: phpdockerio/nginx:latest
      container_name: regexpatterns-webserver
      environment:
          - VIRTUAL_HOST=regexpatterns.dev
      volumes:
          - ./regexpatterns:/var/www/regexpatterns
          - ./docker/regexpatterns-nginx/nginxdev.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - nginx-proxy
      links:
       - regexpatterns-php-fpm


    regexpatterns-memcached:
      image: phpdockerio/memcached:latest
      container_name: regexpatterns-memcached
      depends_on:
        - nginx-proxy

    regexpatterns-mysql:
      image: mysql:5.7
      container_name: regexpatterns-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=db_name
        - MYSQL_USER=db_username
        - MYSQL_PASSWORD=db_password
      depends_on:
        - nginx-proxy


    regexpatterns-php-fpm:
      build: .
      build:
        context: .
        dockerfile: docker/regexpatterns-php-fpm/Dockerfiledev
      depends_on:
        - nginx-proxy
      container_name: regexpatterns-php-fpm
      volumes:
        - ./regexpatterns:/var/www/regexpatterns
        - ./docker/regexpatterns-fpm/php-ini-overridesdev.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./docker/regexpatterns-php-fpm/xdebug.ini:/etc/php/7.1/fpm/conf.d/20-xdebug.ini
      links:
        - regexpatterns-memcached
        - regexpatterns-mysql
      expose:
        - "9000"
      environment: 
        - PHP_XDEBUG_ENABLED 1
#        - XDEBUG_CONFIG: remote_host="192.168.1.20"




