###############################################################################
#                                                    #
# microuser 20170130    Manaully edit for conversion to version 2 from phpdocker.io
#   -   Remove Ports on webserver, replace with link nginx-proxy
#   -   Add depends_on nginx-proxy
#   -   Move regexpatterns-php-fpm dockerfile into build: dockerfile:
###############################################################################
version: '2'

services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
         - 80:80
      volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro


    regexpatterns-webserver:
      image: phpdockerio/nginx:latest
      container_name: regexpatterns-webserver
      environment:
          - VIRTUAL_HOST=iusethis.org,vortexforces.com,regexpatterns.iusethis.org
      volumes:
          - ./regexpatterns/regexpatterns:/var/www/regexpatterns
          - ./regexpatterns/docker/regexpatterns-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - nginx-proxy
      links:
       - regexpatterns-php-fpm


    regexpatterns-memcached:
      image: phpdockerio/memcached:latest
      container_name: regexpatterns-memcached
      depends_on:
        - nginx-proxy

    regexpatterns-mysql:
      image: mysql:5.7
      container_name: regexpatterns-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=db_name
        - MYSQL_USER=secviw3489fosudfjsdjfkjk
        - MYSQL_PASSWORD=sdaf734fshsfdf34lkjsdf8e4hjsdfjsdfj
      depends_on:
        - nginx-proxy


    regexpatterns-php-fpm:
      build: .
      build:
        context: .
        dockerfile: docker/regexpatterns-php-fpm/Dockerfile
      depends_on:
        - nginx-proxy
      container_name: regexpatterns-php-fpm
      environment:
         - XDEBUG_CONFIG=""
      volumes:
        - ./regexpatterns/regexpatterns:/var/www/regexpatterns
        - ./regexpatterns/docker/regexpatterns-php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      links:
        - regexpatterns-memcached
        - regexpatterns-mysql


